### 

import ./auth.http


### getAllImages

run #auth

GET {{HOSTNAME}}/api/v1/images HTTP/1.1
Authorization: Bearer {{auth.response.body.token}}
Content-Type: application/json

# @jq .[]._id


### 
